version: "3.7"

services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15431:5432"
